#!/usr/bin/env python3
"""Generate include/git_info.h with build metadata for the ESP-IDF build.

Captures the Git commit id, branch, and remote author, increments the persistent
build number in .build_number, and writes include/git_info.h. Invoked by
tools/grinder.py before `idf.py build` (and by the release CI):

    python3 tools/build-scripts/pre_build.py --header
"""

import subprocess
import sys
import os
import re

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def get_git_info():
    """Get Git commit ID, branch, and remote author."""
    try:
        # Get current Git commit hash (short form, 7 characters)
        commit_result = subprocess.run(
            ['git', 'rev-parse', '--short=7', 'HEAD'],
            capture_output=True,
            text=True,
            cwd=PROJECT_ROOT
        )

        if commit_result.returncode == 0:
            commit_id = commit_result.stdout.strip()
        else:
            commit_id = "unknown"

        # Get current Git branch
        branch_result = subprocess.run(
            ['git', 'rev-parse', '--abbrev-ref', 'HEAD'],
            capture_output=True,
            text=True,
            cwd=PROJECT_ROOT
        )

        if branch_result.returncode == 0:
            branch = branch_result.stdout.strip()
        else:
            branch = "unknown"

        # Get the GitHub username from the remote URL (shown on the About page)
        remote_result = subprocess.run(
            ['git', 'remote', 'get-url', 'origin'],
            capture_output=True,
            text=True,
            cwd=PROJECT_ROOT
        )

        if remote_result.returncode == 0 and remote_result.stdout.strip():
            match = re.search(r'github\.com[:/]([^/]+)/', remote_result.stdout.strip())
            author = match.group(1) if match else remote_result.stdout.strip()
        else:
            author = "unknown"

        # Check if there are uncommitted changes
        status_result = subprocess.run(
            ['git', 'status', '--porcelain'],
            capture_output=True,
            text=True,
            cwd=PROJECT_ROOT
        )

        if status_result.returncode == 0 and status_result.stdout.strip():
            # There are uncommitted changes, append + to commit ID
            commit_id += "+"

    except (subprocess.SubprocessError, FileNotFoundError):
        # Git not available or not a git repository
        commit_id = "unknown"
        branch = "unknown"
        author = "unknown"

    return commit_id, branch, author


def get_next_build_number():
    """Get and increment the persistent build number."""
    build_number_file = os.path.join(PROJECT_ROOT, ".build_number")

    # Read current build number
    build_number = 1
    if os.path.exists(build_number_file):
        try:
            with open(build_number_file, 'r') as f:
                build_number = int(f.read().strip()) + 1
        except (ValueError, IOError):
            build_number = 1

    # Write incremented build number
    try:
        with open(build_number_file, 'w') as f:
            f.write(str(build_number))
    except IOError as e:
        print(f"Warning: Could not write build number: {e}", file=sys.stderr)

    return build_number


def create_git_info_header():
    """Create include/git_info.h with Git and build information."""
    commit_id, branch, author = get_git_info()

    # Get unique auto-incrementing build number
    build_number = get_next_build_number()

    # Generate timestamp for reference
    from datetime import datetime
    build_timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    header_path = os.path.join(PROJECT_ROOT, "include", "git_info.h")

    header_content = f"""#pragma once

// Auto-generated build information - DO NOT EDIT MANUALLY
// Generated by tools/build-scripts/pre_build.py

#define GIT_COMMIT_ID "{commit_id}"
#define GIT_BRANCH "{branch}"
#define GIT_COMMIT_AUTHOR "{author}"
#define BUILD_NUMBER {build_number}
#define BUILD_TIMESTAMP "{build_timestamp}"
"""

    try:
        with open(header_path, 'w') as f:
            f.write(header_content)
        print(f"Generated {header_path} (Build #{build_number})")
    except Exception as e:
        print(f"Error creating header file: {e}", file=sys.stderr)


def main():
    # `--header` is accepted for backwards compatibility; header generation is
    # the only mode.
    create_git_info_header()


if __name__ == "__main__":
    main()
