// Generated by tools/generate_screensaver_assets.py - do not edit
#pragma once
#include <stdint.h>

#define SCREENSAVER_MEDIA_WIDTH_PX 280
#define SCREENSAVER_MEDIA_HEIGHT_PX 456
#define SCREENSAVER_CAT_FRAME_COUNT 12
#define SCREENSAVER_CAT_FRAME_INTERVAL_MS 125

#ifdef __cplusplus
extern "C" {
#endif

extern const uint8_t screensaver_flower_jpg[];
extern const uint32_t screensaver_flower_jpg_len;

extern const uint8_t* const screensaver_cat_frames[SCREENSAVER_CAT_FRAME_COUNT];
extern const uint32_t screensaver_cat_frame_lens[SCREENSAVER_CAT_FRAME_COUNT];

#ifdef __cplusplus
}
#endif
