#!/usr/bin/env python3
"""Generate embedded screensaver media assets.

Center-crops the inputs to the display aspect ratio, resizes them to the
panel resolution, JPEG-compresses them, and emits C arrays into
src/ui/assets/. The firmware decodes the JPEGs into PSRAM when the
screensaver starts.

Dependencies: pillow, imageio, imageio-ffmpeg. Run with uv:

    uv run --with pillow --with imageio --with imageio-ffmpeg \
        python3 tools/generate_screensaver_assets.py <cat_video> <flower_image>

AVIF flower sources need converting first (macOS): sips -s format png in.avif --out out.png
"""

import io
import sys
from pathlib import Path

import imageio.v3 as iio
from PIL import Image

DISPLAY_WIDTH = 280
DISPLAY_HEIGHT = 456
CAT_FRAME_COUNT = 12
CAT_FRAME_INTERVAL_MS = 125  # 8 fps loop
CAT_JPEG_QUALITY = 78
FLOWER_JPEG_QUALITY = 85

ASSETS_DIR = Path(__file__).resolve().parent.parent / "src" / "ui" / "assets"


def center_crop_resize(image: Image.Image) -> Image.Image:
    target_aspect = DISPLAY_WIDTH / DISPLAY_HEIGHT
    width, height = image.size
    aspect = width / height
    if aspect > target_aspect:
        crop_width = round(height * target_aspect)
        x0 = (width - crop_width) // 2
        image = image.crop((x0, 0, x0 + crop_width, height))
    else:
        crop_height = round(width / target_aspect)
        y0 = (height - crop_height) // 2
        image = image.crop((0, y0, width, y0 + crop_height))
    return image.resize((DISPLAY_WIDTH, DISPLAY_HEIGHT), Image.LANCZOS)


def to_jpeg_bytes(image: Image.Image, quality: int) -> bytes:
    buffer = io.BytesIO()
    image.convert("RGB").save(buffer, format="JPEG", quality=quality, optimize=True)
    return buffer.getvalue()


def emit_byte_array(out, name: str, data: bytes):
    out.write(f"const uint8_t {name}[{len(data)}] = {{\n")
    for offset in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[offset:offset + 16])
        out.write(f"    {chunk},\n")
    out.write("};\n")


def generate_flower(flower_path: Path):
    image = center_crop_resize(Image.open(flower_path))
    data = to_jpeg_bytes(image, FLOWER_JPEG_QUALITY)
    with open(ASSETS_DIR / "screensaver_flower.c", "w") as out:
        out.write("// Generated by tools/generate_screensaver_assets.py - do not edit\n")
        out.write('#include "screensaver_assets.h"\n\n')
        emit_byte_array(out, "screensaver_flower_jpg", data)
        out.write(f"\nconst uint32_t screensaver_flower_jpg_len = {len(data)};\n")
    return len(data)


def generate_cat(cat_path: Path):
    metadata = iio.immeta(cat_path)
    duration = metadata["duration"]
    fps = metadata["fps"]
    total_frames = int(duration * fps)

    frame_sizes = []
    with open(ASSETS_DIR / "screensaver_cat.c", "w") as out:
        out.write("// Generated by tools/generate_screensaver_assets.py - do not edit\n")
        out.write('#include "screensaver_assets.h"\n\n')

        for i in range(CAT_FRAME_COUNT):
            index = min(i * total_frames // CAT_FRAME_COUNT, total_frames - 1)
            frame = iio.imread(cat_path, index=index)
            image = center_crop_resize(Image.fromarray(frame))
            data = to_jpeg_bytes(image, CAT_JPEG_QUALITY)
            frame_sizes.append(len(data))
            emit_byte_array(out, f"screensaver_cat_frame_{i:02d}_jpg", data)
            out.write("\n")

        names = ",\n    ".join(f"screensaver_cat_frame_{i:02d}_jpg" for i in range(CAT_FRAME_COUNT))
        out.write(f"const uint8_t* const screensaver_cat_frames[{CAT_FRAME_COUNT}] = {{\n    {names},\n}};\n")
        sizes = ", ".join(str(size) for size in frame_sizes)
        out.write(f"const uint32_t screensaver_cat_frame_lens[{CAT_FRAME_COUNT}] = {{{sizes}}};\n")
    return sum(frame_sizes)


def generate_header():
    with open(ASSETS_DIR / "screensaver_assets.h", "w") as out:
        out.write(
            "// Generated by tools/generate_screensaver_assets.py - do not edit\n"
            "#pragma once\n"
            "#include <stdint.h>\n"
            "\n"
            f"#define SCREENSAVER_MEDIA_WIDTH_PX {DISPLAY_WIDTH}\n"
            f"#define SCREENSAVER_MEDIA_HEIGHT_PX {DISPLAY_HEIGHT}\n"
            f"#define SCREENSAVER_CAT_FRAME_COUNT {CAT_FRAME_COUNT}\n"
            f"#define SCREENSAVER_CAT_FRAME_INTERVAL_MS {CAT_FRAME_INTERVAL_MS}\n"
            "\n"
            "#ifdef __cplusplus\n"
            'extern "C" {\n'
            "#endif\n"
            "\n"
            "extern const uint8_t screensaver_flower_jpg[];\n"
            "extern const uint32_t screensaver_flower_jpg_len;\n"
            "\n"
            "extern const uint8_t* const screensaver_cat_frames[SCREENSAVER_CAT_FRAME_COUNT];\n"
            "extern const uint32_t screensaver_cat_frame_lens[SCREENSAVER_CAT_FRAME_COUNT];\n"
            "\n"
            "#ifdef __cplusplus\n"
            "}\n"
            "#endif\n"
        )


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 1

    cat_path = Path(sys.argv[1])
    flower_path = Path(sys.argv[2])
    ASSETS_DIR.mkdir(parents=True, exist_ok=True)

    generate_header()
    flower_bytes = generate_flower(flower_path)
    cat_bytes = generate_cat(cat_path)

    print(f"Flower: {flower_bytes} bytes")
    print(f"Cat: {CAT_FRAME_COUNT} frames, {cat_bytes} bytes total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
