# yamllint disable rule:truthy
---
name: Deploy Web Flasher

on:
  push:
    branches:
      - main
    paths:
      - tools/web-flasher/**
  release:
    types:
      - published
      - unpublished
      - deleted
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read
  deployments: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Populate firmware assets from releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          rm -rf tools/web-flasher/firmware
          mkdir -p tools/web-flasher/firmware

          REPO="${{ github.repository }}"
          echo "Fetching release list for $REPO"

          TAGS=$(gh api \
            --paginate \
            --jq 'map(select(.draft == false)) | .[].tag_name' \
            "/repos/${REPO}/releases?per_page=100")

          if [ -z "$TAGS" ]; then
            echo "No published releases found"
            exit 0
          fi

          for TAG in $TAGS; do
            TARGET_DIR="tools/web-flasher/firmware/${TAG}"
            mkdir -p "$TARGET_DIR"
            echo "Downloading assets for $TAG"
            gh release download "$TAG" \
              --repo "$REPO" \
              --dir "$TARGET_DIR" \
              --clobber
          done

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: tools/web-flasher

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
